/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserManagementFrame;

import javax.swing.table.DefaultTableModel;
import java.io.*;
import java.util.*;


/**
 *
 * @author user
 */
public class UserManagementPanel extends javax.swing.JPanel {

    /**
     * Creates new form UserManagementPanel
     */
    public UserManagementPanel() {
        initComponents();

        refreshButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
             loadUserList(); 
         }
        });
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteUser(); 
            }
        });   
        
        loadUserList();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        userIdField = new javax.swing.JTextField();
        userPasswordField = new javax.swing.JPasswordField();
        roleComboBox = new javax.swing.JComboBox<>();
        addButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        userTable = new javax.swing.JTable();
        deleteButton = new javax.swing.JButton();
        refreshButton = new javax.swing.JButton();

        jLabel1.setText("ID");

        jLabel2.setText("Password");

        jLabel3.setText("직급");

        userIdField.addActionListener(this::userIdFieldActionPerformed);

        userPasswordField.addActionListener(this::userPasswordFieldActionPerformed);

        roleComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1. 관리자", "2. 직원(CSR)" }));

        addButton.setText("사용자 추가");
        addButton.addActionListener(this::addButtonActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(13, 13, 13)))
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(userPasswordField)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(roleComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(userIdField)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addComponent(addButton, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(userIdField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(userPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(roleComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        roleComboBox.getAccessibleContext().setAccessibleName("");

        jTabbedPane1.addTab("사용자 추가", jPanel1);

        userTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "역할", "이름", "비고"
            }
        ));
        jScrollPane1.setViewportView(userTable);

        deleteButton.setText("사용자 삭제");

        refreshButton.setText("새로고침");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(deleteButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                .addComponent(refreshButton)
                .addGap(81, 81, 81))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deleteButton)
                    .addComponent(refreshButton))
                .addGap(0, 25, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("사용자 삭제/조회", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        // TODO add your handling code here:
      
        String userId = userIdField.getText();
        String password = new String(userPasswordField.getPassword());
        String role = (String) roleComboBox.getSelectedItem();
      
        if (userId.isEmpty() || password.isEmpty() || role == null) {
            javax.swing.JOptionPane.showMessageDialog(this, "필수 항목을 모두 입력하세요.", "입력 오류", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        try {
            String jsonRequest = "{\"request_type\": \"ADD_USER\", \"data\": {...}}"; 
        
            javax.swing.JOptionPane.showMessageDialog(this, "사용자 추가 성공!", "성공", javax.swing.JOptionPane.INFORMATION_MESSAGE);
        
            userIdField.setText("");
            userPasswordField.setText("");

        } catch (Exception e) {
            
            javax.swing.JOptionPane.showMessageDialog(this, "오류: " + e.getMessage(), "통신 오류", javax.swing.JOptionPane.ERROR_MESSAGE);
            }
        
    }//GEN-LAST:event_addButtonActionPerformed

    private void userIdFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userIdFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userIdFieldActionPerformed

    private void userPasswordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userPasswordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userPasswordFieldActionPerformed

    private void deleteUser() {      
        int selectedRow = userTable.getSelectedRow();
    
        if (selectedRow == -1) {
            javax.swing.JOptionPane.showMessageDialog(this, "삭제할 사용자를 목록에서 선택해주세요.", "선택 오류", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }
 
        DefaultTableModel model = (DefaultTableModel) userTable.getModel();
        String userIdToDelete = model.getValueAt(selectedRow, 0).toString(); 
    
        int confirm = javax.swing.JOptionPane.showConfirmDialog(this,
            "사용자 ID '" + userIdToDelete + "'를 정말 삭제하시겠습니까?", "삭제 확인",
            javax.swing.JOptionPane.YES_NO_OPTION);
    
        if (confirm != javax.swing.JOptionPane.YES_OPTION) {
            return; 
        }
    
        
        try {
            
            String request = "{\"request_type\": \"DELETE_USER\", \"data\": {\"id\": \"" + userIdToDelete + "\"}}";
 
            String jsonResponse = "{\"status\": \"SUCCESS\"}"; 

            if (jsonResponse.contains("\"status\": \"SUCCESS\"")) {
                
                javax.swing.JOptionPane.showMessageDialog(this, "사용자 '" + userIdToDelete + "' 삭제 성공.", "성공", javax.swing.JOptionPane.INFORMATION_MESSAGE);
                
                model.removeRow(selectedRow);
                //loadUserList(); 
            
            } else {
                
                javax.swing.JOptionPane.showMessageDialog(this, "삭제 실패: 권한이 없거나 오류가 발생했습니다.", "오류", javax.swing.JOptionPane.ERROR_MESSAGE);
            }
        
        } catch (Exception e) {
            
            javax.swing.JOptionPane.showMessageDialog(this, "시스템 오류: 서버 통신 실패.", "심각한 오류", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }
    
    
    // ====================================================================
    // 💡 SFR-205 구현 로직 메서드: 사용자 목록을 서버에 요청하고 JTable을 업데이트합니다.
    // ====================================================================
    private void loadUserList() {
        System.out.println("--- DEBUG: loadUserList() 메서드 시작 (SFR-205) ---");
        try {
            // 1. 서버에 목록 요청 (SFR-800 프로토콜 준수)
            String request = "{\"request_type\": \"GET_USER_LIST\", \"data\": {}}";
            String jsonResponse = "{\"status\": \"SUCCESS\", \"data\": [{\"id\":\"admin\", \"role\":\"관리자\"}, {\"id\":\"simhyeonwoo\", \"role\":\"직원(CSR)\"}]}"; 
            
            // 🚨 2. JSON 파싱 및 데이터 모델 변환 코드를 모두 주석 처리합니다.
            // List<User> userList = JsonConverter.getUsersFromResponse(jsonResponse); 
            // for (User user : userList) { ... }
            
            String[] columnNames = {"ID", "역할"}; // 💡 실제 표시할 열 이름
            DefaultTableModel model = new DefaultTableModel(columnNames, 0); 
            
            model.addRow(new Object[]{"admin", "관리자"}); 
            model.addRow(new Object[]{"simhyeonwoo", "직원(CSR)"});
            
            userTable.setModel(model); 
            // 5. Output에 성공 메시지 출력 (실행 완료 확인)
            System.out.println("--- DEBUG: 사용자 목록 테이블 업데이트 성공! ---");
            
            userTable.getColumnModel().getColumn(0).setPreferredWidth(50); 
            
        } catch (Exception e) {
            System.err.println("❌ Load List Exception: " + e.getMessage()); 
            e.printStackTrace();
            
            javax.swing.JOptionPane.showMessageDialog(this, "목록 로드 실패: " + e.getMessage(), "오류", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
        // loadUserList() 메서드의 userTable.setModel(model) 이후에 추가
        // 💡 userTable.getColumnModel().getColumn(3)의 경우, 비밀번호 Hash가 들어가지 않으므로
        // 이 열이 UI에 표시되지 않도록 숨기는 처리도 고려
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JButton deleteButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JButton refreshButton;
    private javax.swing.JComboBox<String> roleComboBox;
    private javax.swing.JTextField userIdField;
    private javax.swing.JPasswordField userPasswordField;
    private javax.swing.JTable userTable;
    // End of variables declaration//GEN-END:variables
}
