/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package MainAppFrame;
import javax.swing.JFrame; // JFrame을 사용하기 위해 필요
import java.awt.BorderLayout; // BorderLayout을 사용하기 위해 필요

import UserManagementFrame.UserManagementPanel;

/**
 *
 * @author user
 */
public class AppFrame extends javax.swing.JFrame {

    /**
     * Creates new form java
     */
    public AppFrame() {
        // JFrame 관련 설정을 수동으로 추가합니다.
        setTitle("HotelFlow - 사용자 관리 시스템");
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE); // 창 닫기 버튼 설정
        
        // NetBeans가 생성한 UI 초기화 (현재 비어 있음)
        initComponents();
        
        this.getContentPane().setLayout(new java.awt.BorderLayout()); 
    
        // 💡 UserManagementPanel 인스턴스 생성
        UserManagementPanel userPanel = new UserManagementPanel();
    
        // 2. UserPanel을 ContentPane의 중앙에 추가
        this.getContentPane().add(userPanel, java.awt.BorderLayout.CENTER);
        
        // 창 크기 자동 조정 및 표시
        pack(); 
        setLocationRelativeTo(null);
        
        
    }
    
    // =======================================================
    // 메인 메서드: 애플리케이션의 진입점
    public static void main(String args[]) {
        // AWT EventQueue를 사용하여 Swing 컴포넌트가 스레드 안전하게 실행되도록 보장
        java.awt.EventQueue.invokeLater(new Runnable() { 
            public void run() {
                // AppFrame 인스턴스를 생성하고 보이게 설정
                new AppFrame().setVisible(true); 
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
